<link rel="stylesheet" href="{{ asset('page_dist/css/linearicons.css') }}">
<link rel="stylesheet" href="{{ asset('page_dist/css/font-awesome.min.css') }}">
<link rel="stylesheet" href="{{ asset('page_dist/css/bootstrap.css') }}">
<link rel="stylesheet" href="{{ asset('page_dist/css/magnific-popup.css') }}">
<link rel="stylesheet" href="{{ asset('page_dist/css/nice-select.css') }}">
<link rel="stylesheet" href="{{ asset('page_dist/css/animate.min.css') }}">
<link rel="stylesheet" href="{{ asset('page_dist/css/owl.carousel.css') }}">
<link rel="stylesheet" href="{{ asset('page_dist/css/jquery-ui.css') }}">
<link rel="stylesheet" href="{{ asset('page_dist/css/main.css') }}">